### ISSUE TITLE
ncaught Error: addCase cannot be called with two reducers for the same action type

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#28]
1. 오류 상황
![image](https://user-images.githubusercontent.com/109063966/187953946-f8494943-f14a-4aaf-83ec-884bbbc1a821.png)

>   Uncaught Error: addCase cannot be called with two reducers for the same action type
    at Object.addCase (mapBuilders.ts:163:1)
    at extraReducers (detailSlice.jsx:81:1)
    at executeReducerBuilderCallback (mapBuilders.ts:194:1)
    at buildReducer (createSlice.ts:310:1)
    at reducer (createSlice.ts:333:1)
    at redux.js:468:1
    at Array.forEach (<anonymous>)
    at assertReducerShape (redux.js:466:1)
    at combineReducers (redux.js:531:1)
    at ./src/store.js (store.js:4:1)

2. 해결
thunk 부분의 주소가 겹쳐서 일어났다. 주소를 상이하게 해주면 된다.

**Comment by caffesale** [comment]
Branch [issue-28](https://github.com/shoesbox/shoesbox-fe/tree/issue-28) created!
