### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#35]
1. 오류 발생
![image](https://user-images.githubusercontent.com/109063966/188150470-b076bd66-eebb-4a17-b549-87e8e99ebd92.png)

> Uncaught (in promise) TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at WritePage.jsx:59:1
    at new Promise (<anonymous>)
    at encodeFileToBase64 (WritePage.jsx:56:1)
    at WritePage.jsx:70:1
    at Array.forEach (<anonymous>)
    at WritePage.jsx:69:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)

2. 해결
오타를 잘 발견하자
`  const onChangePic = (e) => {
    setFiles(e.target.value);
  };
`
`  const onChangePic = (e) => {
    setFiles(e.target.files);
  };
`

**Comment by caffesale** [comment]
Branch [issue-35](https://github.com/shoesbox/shoesbox-fe/tree/issue-35) created!

**Comment by akashhdeep** [comment]
@lovysunny7 You got any solution for this?
I'm stuck with the same issue
